# Generated by Django 4.1.7 on 2023-02-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="duration",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name="movie",
            name="synopsis",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
