# Generated by Django 4.1.7 on 2023-02-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_movieorder_movie_movieorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="buyed_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
